# Generated by Django 3.2.3 on 2021-05-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('manager_mail', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('deadline1', models.DateField()),
                ('deadline2', models.DateField()),
                ('deadline3', models.DateField()),
            ],
        ),
    ]
